### ISSUE TITLE
How to install external shared library?

### ISSUE THREAD

**Issue by nekketsuuu** [melpon/wandbox-builder#12]
I'm trying to build the SML# compiler on Wandbox.
However, the compiler needs some libraries such as LLVM 3.7.1,  [YAJL 2](https://github.com/lloyd/yajl) and [MassiveThreads 0.99](https://github.com/massivethreads/massivethreads), which are not installed in `melpon/wandbox:test-server`. They are required not only to build the compiler, but also to run that.

Therefore, when I tested the compiler, it outputted some errors as follows.
```
/opt/wandbox/smlsharp-3.3.0/bin/smlsharp: error while loading shared libraries: libLLVM-3.7.so.1: cannot open shared object file: No such file or directory
```

These libraries except for MassiveThreads are indeed necessary; the details are written in [§5.3 of the document of SML#](http://www.pllab.riec.tohoku.ac.jp/smlsharp/docs/3.3.0/en/Ch5.S3.xhtml).

How should I handle this problem? For example, should I self-compile the libraries like Boost library does?

**Comment by melpon** [comment]
I do not want to install additional libraries on the running server whenever possible. So link the library statically.

If SML# has a static link option, specify one. Otherwise, force link statically like [this](https://github.com/melpon/wandbox-builder/blob/74efd700d3c146d35c5aec466531125018ac1b44/build/ldc/install.sh#L34).

**Comment by nekketsuuu** [comment]
Thank you for your quick reply. I'll try it.
